package cz.cvut.fel.omo.smarthome.eventhandler.events;

public enum EventType {
    START_USING_APPLIANCE,
    STOP_USING_APPLIANCE,
    BREAK_APPLIANCE,
    APPLIANCE_REPAIRED,
    PERSON_MOVE_EVENT,
    START_USING_SPORT_ITEM,
    STOP_USING_SPORT_ITEM,

    PET_MOVE_EVENT,

    TURN_ON_APPLIANCE,
    TURN_OFF_APPLIANCE,
    TURN_IDLE_APPLIANCE,
    TURN_BROKEN_APPLIANCE,
    TASK_FINISHED,

    ADD_ITEM_TO_FOOD,
    REMOVE_ITEM_TO_FOOD,

    ROLL_BLINDS,

    NEXT_CYCLE_EVENT;
}
